### ISSUE TITLE
Suggestion: use setComponentEnabledSetting instead of checking preference each time there is an event

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [seguri/GetForegroundActivity#1]
This is not needed:

```
@Override
public void onAccessibilityEvent(AccessibilityEvent event) {
    boolean isServiceActive = Utils.getSharedPref(this, R.string.sharedprefs_key1, false);
    if (isServiceActive...
```

You can just disable&enable the service, as such:

```
public static void setEnabled(Context context, boolean enabled) {
    ComponentName component = new ComponentName(context, WindowChangeDetectingService.class);
    context.getPackageManager().setComponentEnabledSetting(component,
            enabled ? PackageManager.COMPONENT_ENABLED_STATE_ENABLED : PackageManager.COMPONENT_ENABLED_STATE_DISABLED, PackageManager.DONT_KILL_APP);
}
```

Also, I'd like to ask: do you know perhaps how to use this service to get views info from the currnet screen? Someone said it's posible using "dump" , but I can't find any sample or tutorial about it.

**Comment by seguri** [comment]
Hello @AndroidDeveloperLB,
I'm currently not managing service life; why should I start doing it?

**Comment by AndroidDeveloperLB** [comment]
@seguri  The sample has a switch view, to turn the service on&off, yet the way it works is that when it's turned off, the service is still alive and just ignores the data it gets.

Disabling and enabling should be on the service itself, not just a sharedPreference .

**Comment by seguri** [comment]
@AndroidDeveloperLB I'm testing your code and it is not working correctly (sometimes it starts, sometimes it stops). Are you sure this is the right way to manage an accessibility service?

**Comment by AndroidDeveloperLB** [comment]
I think for any service, and not just accessibility . 
What do you mean "sometimes it starts, sometimes it stops" ? The code only sets whether the component will be enabled or not.
A similar one would be for checking if the component is enabled or not.

**Comment by seguri** [comment]
Watch this code:

```java
@Override
public boolean onCreateOptionsMenu(Menu menu) {
    getMenuInflater().inflate(R.menu.menu_main, menu);
    MenuItem switchItem = menu.findItem(R.id.toggleservice);
    mSwitch = (Switch) switchItem.getActionView();
    mSwitch.setOnCheckedChangeListener(this::manageAccessibilityService);
    return super.onCreateOptionsMenu(menu);
}

/**
 * Start/stop accessibility server based on switch button status.
 * @param button ignored
 * @param isChecked button status
 */
private void manageAccessibilityService(CompoundButton button, boolean isChecked){
    ComponentName component = new ComponentName(this, WindowChangeDetectingService.class);
    int newState = isChecked ? PackageManager.COMPONENT_ENABLED_STATE_ENABLED : PackageManager.COMPONENT_ENABLED_STATE_DISABLED;
    Log.i(TAG, (isChecked ? "Enabling" : "Disabling") + " accessibility service (newState=" + newState + ")");
    getPackageManager().setComponentEnabledSetting(component, newState, PackageManager.DONT_KILL_APP);
}
```

Have I correctly understood the behaviour of `setComponentEnabledSetting`?

**Comment by seguri** [comment]
Taken from [the *Lifecycle* section of the `AccessibilityService` documentation][1]:

> The lifecycle of an accessibility service is managed exclusively by the system and follows the established service life cycle. Starting an accessibility service is triggered exclusively by the user explicitly turning the service on in device settings. After the system binds to a service, it calls [`onServiceConnected()`][2]. This method can be overriden by clients that want to perform post binding setup.

> An accessibility service stops either when the user turns it off in device settings or when it calls [`disableSelf()`][3].


  [1]: https://developer.android.com/reference/android/accessibilityservice/AccessibilityService.html
  [2]: https://developer.android.com/reference/android/accessibilityservice/AccessibilityService.html#onServiceConnected()
  [3]: https://developer.android.com/reference/android/accessibilityservice/AccessibilityService.html#disableSelf()

**Comment by AndroidDeveloperLB** [comment]
Odd. Was sure it works. Will need to check it further.
BTW, to check if this service is enabled, you can use this:
http://stackoverflow.com/a/40568194/878126

**Comment by AndroidDeveloperLB** [comment]
Can you also answer about how to get views sizes&positions using the accessibility service?

**Comment by AndroidDeveloperLB** [comment]
I've posted a question about whether it's possible to enable&disable the service here:
http://stackoverflow.com/q/41785005/878126
